//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infraestructura.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos fueron actualizados....
        /// </summary>
        public static string ActualizacionCorrecta {
            get {
                return ResourceManager.GetString("ActualizacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea anular este registro?.
        /// </summary>
        public static string AdvertenciaAnulacion {
            get {
                return ResourceManager.GetString("AdvertenciaAnulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de eliminar los datos?.
        /// </summary>
        public static string AdvertenciaEliminacion {
            get {
                return ResourceManager.GetString("AdvertenciaEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Imprimir comprobante?.
        /// </summary>
        public static string AdvertenciaImpresionComprobante {
            get {
                return ResourceManager.GetString("AdvertenciaImpresionComprobante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Anulado..
        /// </summary>
        public static string AnulacionCorrecta {
            get {
                return ResourceManager.GetString("AnulacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea actualizar los datos?.
        /// </summary>
        public static string AvisoActualizacion {
            get {
                return ResourceManager.GetString("AvisoActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea anular el registro?.
        /// </summary>
        public static string AvisoAnulacion {
            get {
                return ResourceManager.GetString("AvisoAnulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de eliminar el registro?.
        /// </summary>
        public static string AvisoEliminacion {
            get {
                return ResourceManager.GetString("AvisoEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Desea eliminar la fila?.
        /// </summary>
        public static string AvisoEliminarFila {
            get {
                return ResourceManager.GetString("AvisoEliminarFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de guardar los datos?.
        /// </summary>
        public static string AvisoGrabacion {
            get {
                return ResourceManager.GetString("AvisoGrabacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de cambiar el codigo de muestra?.
        /// </summary>
        public static string CambiarCodigoMuestra {
            get {
                return ResourceManager.GetString("CambiarCodigoMuestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codigo ya existe.
        /// </summary>
        public static string CodigoExistente {
            get {
                return ResourceManager.GetString("CodigoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Eliminado.. !!.
        /// </summary>
        public static string EliminacionCorrecta {
            get {
                return ResourceManager.GetString("EliminacionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos eliminados correctamente.
        /// </summary>
        public static string EliminacionExitosa {
            get {
                return ResourceManager.GetString("EliminacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado, consulte con el administrador..
        /// </summary>
        public static string ErrorInesperado {
            get {
                return ResourceManager.GetString("ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una temporada vigente: {0}.
        /// </summary>
        public static string ExisteTemporadaVigente {
            get {
                return ResourceManager.GetString("ExisteTemporadaVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta ingresar campos.
        /// </summary>
        public static string FaltaIngresarCampos {
            get {
                return ResourceManager.GetString("FaltaIngresarCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se Generó las Ordenes de Compra Correctamente.
        /// </summary>
        public static string GeneracionOrdenCompra {
            get {
                return ResourceManager.GetString("GeneracionOrdenCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la asignacion de Tarjetas Correctamente.
        /// </summary>
        public static string GrabacionAsignacionTarjetas {
            get {
                return ResourceManager.GetString("GrabacionAsignacionTarjetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudieron grabar los datos.
        /// </summary>
        public static string GrabacionErronea {
            get {
                return ResourceManager.GetString("GrabacionErronea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos grabados correctamente.
        /// </summary>
        public static string GrabacionExitosa {
            get {
                return ResourceManager.GetString("GrabacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó el requerimiento correctamente.
        /// </summary>
        public static string GrabacionRequerimiento {
            get {
                return ResourceManager.GetString("GrabacionRequerimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjetas generadas correctamente.
        /// </summary>
        public static string GrabacionTarjetasExitosa {
            get {
                return ResourceManager.GetString("GrabacionTarjetasExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea aprobar esta orden?.
        /// </summary>
        public static string MSG_APROBAR_ORDEN {
            get {
                return ResourceManager.GetString("MSG_APROBAR_ORDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea Eliminar Rubro?.
        /// </summary>
        public static string MSG_GBL_CONFIRMA_ELIMINAR_RUBRO {
            get {
                return ResourceManager.GetString("MSG_GBL_CONFIRMA_ELIMINAR_RUBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de grabar los datos?.
        /// </summary>
        public static string MSG_GBL_CONFIRMA_GRABACION {
            get {
                return ResourceManager.GetString("MSG_GBL_CONFIRMA_GRABACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Opcion.
        /// </summary>
        public static string MSG_GBL_ELIJA_OPCION {
            get {
                return ResourceManager.GetString("MSG_GBL_ELIJA_OPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso se ejecutó correctamente..
        /// </summary>
        public static string MSG_GBL_OK {
            get {
                return ResourceManager.GetString("MSG_GBL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este Rubro ya se encuentra Seleccionado..
        /// </summary>
        public static string MSG_GBL_RUBRO_DUPLICADO {
            get {
                return ResourceManager.GetString("MSG_GBL_RUBRO_DUPLICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consulta ejecutada no recuperó registros..
        /// </summary>
        public static string MSG_GBL_SIN_REGISTROS {
            get {
                return ResourceManager.GetString("MSG_GBL_SIN_REGISTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que desea generar la solicitud de producciòn?.
        /// </summary>
        public static string MSG_GENERAR_SOLICITUD_PRODUCCION {
            get {
                return ResourceManager.GetString("MSG_GENERAR_SOLICITUD_PRODUCCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos grabados correctamente..
        /// </summary>
        public static string MSG_GLB_DATOS_GRABADOS {
            get {
                return ResourceManager.GetString("MSG_GLB_DATOS_GRABADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ya exite un registro con las caracteristicas elegidas..
        /// </summary>
        public static string MSG_GLB_EXISTE {
            get {
                return ResourceManager.GetString("MSG_GLB_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrando del {0} al {1} de {2}.
        /// </summary>
        public static string MSG_GRD_MOSTRANDO {
            get {
                return ResourceManager.GetString("MSG_GRD_MOSTRANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página {0}.
        /// </summary>
        public static string MSG_GRD_PAGINA {
            get {
                return ResourceManager.GetString("MSG_GRD_PAGINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera página.
        /// </summary>
        public static string MSG_GRD_PAGINA_PRIMERA {
            get {
                return ResourceManager.GetString("MSG_GRD_PAGINA_PRIMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última página.
        /// </summary>
        public static string MSG_GRD_PAGINA_ULTIMA {
            get {
                return ResourceManager.GetString("MSG_GRD_PAGINA_ULTIMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron resultados..
        /// </summary>
        public static string MSG_GRD_SIN_RESULTADOS {
            get {
                return ResourceManager.GetString("MSG_GRD_SIN_RESULTADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grabación Exitosa - Nro Correlativo : .
        /// </summary>
        public static string MSG_NRO_CORRELATIVO {
            get {
                return ResourceManager.GetString("MSG_NRO_CORRELATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Monto Asignado Supera Ingresado para este Centro de Costo.
        /// </summary>
        public static string MSG_VALIDA_MontoCentroCosto {
            get {
                return ResourceManager.GetString("MSG_VALIDA_MontoCentroCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar un Documento Referencia.
        /// </summary>
        public static string MSG_VALIDA_NOTACREDITO {
            get {
                return ResourceManager.GetString("MSG_VALIDA_NOTACREDITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se Solicita Recalcular el Monto asignado para Centro de Costo..
        /// </summary>
        public static string MSG_VALIDA_RecalcularMontoCentroCosto {
            get {
                return ResourceManager.GetString("MSG_VALIDA_RecalcularMontoCentroCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Monto Ingresado no debe ser Superior al Monto Total.
        /// </summary>
        public static string MSG_ValidarMontoTotalCPP {
            get {
                return ResourceManager.GetString("MSG_ValidarMontoTotalCPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo validar las credenciales ingresadas. Por favor confirme datos.
        /// </summary>
        public static string MSG_VLD_USUARIO_NOVALIDO {
            get {
                return ResourceManager.GetString("MSG_VLD_USUARIO_NOVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea actualizar los datos?.
        /// </summary>
        public static string msgGlbDatosActualizados {
            get {
                return ResourceManager.GetString("msgGlbDatosActualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de realizar el ajuste de tarjetas?.
        /// </summary>
        public static string RealizarAjusteTarjeta {
            get {
                return ResourceManager.GetString("RealizarAjusteTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a validacion de entidad articulo.
        /// </summary>
        public static string ValidacionArticulo {
            get {
                return ResourceManager.GetString("ValidacionArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a validacion de Combo.
        /// </summary>
        public static string ValidacionCombo {
            get {
                return ResourceManager.GetString("ValidacionCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a validacion de entidad producto.
        /// </summary>
        public static string ValidacionProducto {
            get {
                return ResourceManager.GetString("ValidacionProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Necesario Registrar una Cuenta por Pagar..
        /// </summary>
        public static string validar_RegistroCuentaPorPagar {
            get {
                return ResourceManager.GetString("validar_RegistroCuentaPorPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar una Glosa..
        /// </summary>
        public static string validarGlosa {
            get {
                return ResourceManager.GetString("validarGlosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Monto IGV.
        /// </summary>
        public static string validarIGV {
            get {
                return ResourceManager.GetString("validarIGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe Seleccionar un Proveedor..
        /// </summary>
        public static string validarIngresoProveedor {
            get {
                return ResourceManager.GetString("validarIngresoProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Monto Afecto.
        /// </summary>
        public static string validarMontoAfecto {
            get {
                return ResourceManager.GetString("validarMontoAfecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Monto Inafecto.
        /// </summary>
        public static string validarMontoInafecto {
            get {
                return ResourceManager.GetString("validarMontoInafecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Monto Total.
        /// </summary>
        public static string validarMontoTotal {
            get {
                return ResourceManager.GetString("validarMontoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Número de Cuenta..
        /// </summary>
        public static string validarNroCuenta {
            get {
                return ResourceManager.GetString("validarNroCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar Número de Documento.
        /// </summary>
        public static string validarNumeroDocumento {
            get {
                return ResourceManager.GetString("validarNumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \n Ingresar Número de Serie..
        /// </summary>
        public static string validarSerieDocumento {
            get {
                return ResourceManager.GetString("validarSerieDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se realizó el ajuste de tarjetas.
        /// </summary>
        public static string YaFueAjustado {
            get {
                return ResourceManager.GetString("YaFueAjustado", resourceCulture);
            }
        }
    }
}
